AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy S3 Static Website Bucket
Resources:
  S3StaticWebSite:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: slackr
      Tags:
        - Key: App
          Value: Slackr
      WebsiteConfiguration:
        IndexDocument: index.html
Outputs:
  WebSiteURL:
    Value: !GetAtt
      - S3StaticWebSite
      - WebsiteURL
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3StaticWebSite
          - DomainName
