name: Build and deploy React app to AWS S3 - tripblogger

on:
  push:
    branches:
      - feature/deploy-aws
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: react-app
          path: ./build/

      - name: Sync S3 Bucket
        run: |
          aws s3 sync ./build/ s3://slackr/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: us-east-2

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#      - name: Sync S3 Bucket
#        run: |
#          aws s3 sync ./build/ s3://slackr/
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
#          AWS_DEFAULT_REGION: us-east-2

