name: Build and deploy React app to AWS S3 - tripblogger

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  cloud-formation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync CloudFormation Templates
        run: |
          aws s3 sync ./aws/ s3://md-cfn-templates/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: us-east-2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-2

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: SlackerWebSiteS3
          template: ./aws/S3-template.yaml

  build:
    runs-on: ubuntu-latest
    needs: cloud-formation

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: react-app
          path: ./build/

      - name: Sync S3 Bucket
        run: |
          aws s3 sync ./build/ s3://slackr/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: us-east-2
